name: Release

on:
  pull_request:
    paths:
      - .github/workflows/release.yml
      - ./scripts/release_notes
      - .goreleaser.yml
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Generate release notes
        run: |
          ./scripts/release_notes > /tmp/RELEASE_NOTES

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release ${{ github.event_name == 'pull_request' && '--snapshot' || '' }} --clean --release-notes=/tmp/RELEASE_NOTES
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
